name: "EVCC to PDF"
description: "EVCC Abrechnung als PDF"
version: "1.0.1"
slug: "evcc_to_pdf"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386

map:
  - type: share
    read_only: false

options:
  evcc_url: "http://evcc.local:7070"
  evcc_password: ""
  grid_price: 0.35
  selected_vehicles: ""

schema:
  evcc_url: str
  evcc_password: password?
  grid_price: float
  selected_vehicles: str?
